import { BaseLayout } from '@/widgets/layouts';
import { Metadata } from 'next';
import type { AppProps } from 'next/app';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function App({ Component, pageProps }: AppProps) {
	return (
		<BaseLayout>
			<Component {...pageProps} />
		</BaseLayout>
	);
}
